[general]
import = [
  "~/.cache/wal/colors-alacritty.toml",
]

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font]
size = 12.0

[window]

opacity = 0.8

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Light" # "Dark"

